site_name: ANY.RUN Tools
site_description: Python SDK for ANY.RUN APIs
site_author: ANY.RUN
site_url: https://bykovk-pro.github.io/anyrun-tools

repo_name: anyrun/anyrun-tools
repo_url: https://github.com/bykovk-pro/anyrun-tools
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quickstart.md
  - Examples:
    - Sandbox:
      - File Analysis: examples/sandbox/analyze-file.py
      - Task Monitoring: examples/sandbox/monitor-task.py
    - TI Lookup:
      - Hash Lookup: examples/ti-lookup/lookup-hash.py
    - TI YARA:
      - Rule Matching: examples/ti-yara/match-rule.py
  - Contributing: contributing.md
