name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]

    - name: Configure Git user
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Build and deploy docs
      run: |
        set -x
        mike delete --all  # Clean up old versions

        # If this is a tag, deploy that version
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          mike deploy --push --update-aliases $VERSION latest
        # If this is the main branch, deploy to dev
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          mike deploy --push dev
        fi

        # Always build the docs to check for errors in PRs
        mike list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
