name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Check unused imports
      run: |
        autoflake --check --remove-all-unused-imports --recursive src tests

    - name: Run isort
      run: |
        isort --check-only --diff src tests

    - name: Run black
      run: |
        black --check --diff src tests

    - name: Run flake8
      run: |
        flake8 src tests

    - name: Run mypy
      run: |
        mypy src tests

    - name: Security check with bandit
      run: bandit -r src

    - name: Check dependencies with safety
      uses: pyupio/safety@2.3.5
      with:
        scan: 'pyproject.toml'
